version: '3'
services: 
      
  # ------------------------------------------------
  # Apache Zookeeper to ensure Kafka consistency
  # ------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  # ------------------------------------------------
  # Apache KAFKA Message broker
  # ------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stocks_ticks:1:1"
    extra_hosts:
      - "moby:127.0.0.1"
      
  # ------------------------------------------------
  # DataStax Enterprise
  # ------------------------------------------------
  dse:
    image: datastax/dse-server:6.7.0
    command: [ -s -g -k ]
    ports:
      - "9042:9042"
      - "8983:8983"
      - "8182:8182"
    #depends_on:
    #   - opscenter  
    environment:
      - DS_LICENSE=accept
      - DC=DC1
      - JVM_EXTRA_OPTS=-Xmx2g -Xms2g
      - NUM_TOKENS=32
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  # ------------------------------------------------
  # One instance of DataStax Studio
  # ------------------------------------------------
  studio:
     image: datastax/dse-studio:6.7.0
     ports:
       - "9091:9091"
     depends_on:
       - dse
     environment:
       DS_LICENSE: accept
     volumes:
       - "/tmp/docker/studio-notebooks:/var/lib/datastax-studio"
  
  # ------------------------------------------------
  # OpsCenter 6.7.0
  # ------------------------------------------------
  #opscenter:
  #  image: "datastax/dse-opscenter:6.7.0"
  #  ports:
  #    - 8888:8888
  #  environment:
  #    - DS_LICENSE=accept    
  
  # Message broker
  kafka:
    image: confluentinc/cp-kafka:5.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stocks_ticks:1:1"
    extra_hosts:
      - "moby:127.0.0.1"
      
  kafkahq:
    image: tchiotludo/kafkahq
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
    ports:
      - "8080:8080"
    depends_on:
      - kafka         
      