version: '3'

services:

 # --------------------------------
 # DataStax Enterprise
 # --------------------------------
 dse:
    image: datastax/dse-server:6.7.0
    command: [ -s -g -k ]
    ports:
    - "9042:9042"
    - "8983:8983"
    - "8182:8182"
    environment:
      DS_LICENSE: accept
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
      
 # One instance of DataStax Studio
 studio:
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091"
    depends_on:
      - dse
    environment:
      DS_LICENSE: accept
    volumes:
      - "/tmp/docker/studio-notebooks:/var/lib/datastax-studio"

 # Ensure consistency in Kafka World
 zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

 # Start the Kafka Engine for Killrvideo
 kafka:
    image: wurstmeister/kafka:1.0.0
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stocks-ticks:1:1"
    ports:
      - 9092:9092

 kafkahq:
    image: tchiotludo/kafkahq
    environment:
      KAFKAHQ_CONFIGURATION: |
        {
          kafka {
            connections {
              docker-kafka-server {
                  bootstrap.servers: "kafka:9092"
              }
            }
          }
        }
    ports:
      - "8080:8080"
    depends_on:
      - kafka       